#!/bin/sh

# shellcheck disable=SC2034

TOOLS_DIR=./tools
TOOLS_LIST="

# Install commitlint executable
commitlint-install

# Git hooks stopping you from commiting if commitlint fails
commitlint-git-hooks

# Initialize Git submodules automatically
git-init-submodules

# Enable direnv automatically after install
direnv-enable
"

COMMITLINT_USE_GLOBAL_EXECUTABLE=0
